name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      USERNAME_API: ${{ secrets.USERNAME_API }}
      PASSWORD_API: ${{ secrets.PASSWORD_API }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        rsync -avz --delete --exclude '.git' ./ $EC2_USER@$EC2_HOST:/home/ubuntu/webscraper
        ssh $EC2_USER@$EC2_HOST 'cd /home/ubuntu/webscraper && npm install'

    - name: Create .env file on EC2
      run: |
        ssh $EC2_USER@$EC2_HOST "echo 'USERNAME_API=${USERNAME_API}' > /home/ubuntu/webscraper/.env"
        ssh $EC2_USER@$EC2_HOST "echo 'PASSWORD_API=${PASSWORD_API}' >> /home/ubuntu/webscraper/.env"
        ssh $EC2_USER@$EC2_HOST "echo 'JWT_SECRET=${JWT_SECRET}' >> /home/ubuntu/webscraper/.env"
        ssh $EC2_USER@$EC2_HOST "pm2 restart all"
